#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

last_values_file="/tmp/bandwidth_last_values.txt"


stats=$(netstat -ien)

downloaded=$(echo "$stats" | grep 'RX packets' | awk '{print $5}' | tr '\n' '+' | sed 's/+$//g')
uploaded=$(echo "$stats" | grep 'TX packets' | awk '{print $5}' | tr '\n' '+' | sed 's/+$//g')

total_downloaded=$(qalc -t -s "maxdeci 2" "$downloaded")
total_uploaded=$(qalc -t -s "maxdeci 2" "$uploaded")

last_downloaded=0
last_uploaded=0

if [[ -f "$last_values_file" ]]; then
    read last_downloaded last_uploaded < "$last_values_file"
fi

echo -e "$total_downloaded\\t$total_uploaded" > "$last_values_file"

current_downloaded=$(qalc -t -s "maxdeci 2" "($total_downloaded - $last_downloaded)/5 to MB" | sed 's/ MB//g')
current_uploaded=$(qalc -t -s "maxdeci 2" "($total_uploaded - $last_uploaded)/5 to MB" | sed 's/ MB//g')

total_downloaded=$(qalc -t -s "maxdeci 2" "$total_downloaded to GB" | sed 's/ GB//g')
total_uploaded=$(qalc -t -s "maxdeci 2" "$total_uploaded to GB" | sed 's/ GB//g')

echo "D:${total_downloaded}G (${current_downloaded}M/s) U:${total_uploaded}G (${current_uploaded}M/s)"
echo "D:$total_downloaded U:$total_uploaded"
echo "#95e454"
