#!/bin/bash

source "${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/wombat.sh"

cpu=$(mpstat 1 1 | awk '$12 ~ /[0-9.]+/ { print 100 - $12"%" }' | tail -n 1)
temp=$(sensors | grep "CPU" | cut -d'+' -f2 | cut -d' ' -f1)

# full_text
echo "CPU:$cpu $temp"
# short_text
echo "CPU:$cpu"

# Get just the number
cpu_num=$(echo $cpu | cut -d'%' -f1)

# Use bc for comparisons
if (( $(echo "$cpu_num < 60" | bc -l) )); then
    echo "$wombat_blue"
elif (( $(echo "$cpu_num < 90" | bc -l) )); then
    echo "$wombat_yellow"
else
    echo "$wombat_red"
fi
