#!/bin/bash

df_output=$(df -h /)
df_output=$(echo "$df_output" | tail -n 1)
size=$(echo "$df_output" | awk '{print $2}')
used=$(echo "$df_output" | awk '{print $3}')
avail=$(echo "$df_output" | awk '{print $4}')
percent=$(echo "$df_output" | awk '{print $5}' | sed 's/%//')

echo "Disk: $used/$size ($percent%)"
echo "/:$avail"


if (( $(echo "$percent < 80" | bc -l) )); then
    echo "#FFFFFF"
elif (( $(echo "$percent < 90" | bc -l) )); then
    echo "#FF8000"
else
    echo "#FF0000"
fi
