#!/bin/bash

device=$(ip route | grep default | awk '{print $5}' | head -n1)

if [[ -z "$device" ]]; then
    echo "No Network"
    echo "down"
    echo "#9c998e"
    exit 0
fi

ip=$(ip addr show $device | grep -Po 'inet \K[\d.]+')

echo "$device:$ip"
echo $ip
echo "#95e454"
exit 0
