#!/bin/bash

state=$(playerctl status 2> /dev/null)

if [[ $state = "Playing" ]]; then
    echo ""
    echo ""
elif [[ $state = "Paused" ]]; then
    echo ""
    echo ""
else
    echo ""
    echo ""
fi

echo "#FFFFFF"
