#!/bin/bash

source "${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/wombat.sh"

state=$(playerctl status 2> /dev/null)

if [[ $state = "Playing" ]]; then
    echo ">"
    echo ">"
elif [[ $state = "Paused" ]]; then
    echo "||"
    echo "||"
else
    echo ""
    echo ""
fi

echo "$wombat_fg"
