#!/bin/bash

free_output=$(free -h)
total_mem=$(echo "$free_output" | grep Mem | awk '{print $2}')
used_mem=$(echo "$free_output" | grep Mem | awk '{print $3}')

total_num=$(free -b | grep Mem | awk '{print $2}')
used_num=$(free -b | grep Mem | awk '{print $3}')

used_persentage=$(echo "scale=2; $used_num/$total_num*100" | bc | sed 's/\..*//g')

echo "RAM: $used_mem/$total_mem $used_persentage%"
echo "R:$used_persentage%"

if (( $(echo "$used_persentage < 70" | bc -l) )); then
    echo "#ADD8E6"
elif (( $(echo "$used_persentage < 90" | bc -l) )); then
    echo "#FF8000"
else
    echo "#FF0000"
fi
