# Generated by @themes/wombat/generate.py. Edit palette.json instead.
wombat_fg='#e3e0d7'
wombat_muted='#9c998e'
wombat_blue='#88b8f6'
wombat_green='#cae982'
wombat_yellow='#eae788'
wombat_red='#e5786d'
