vim.keymap.set('n', '<leader>ff', ':Files<CR>')
vim.keymap.set('n', '<leader>fb', ':Buffers<CR>')
vim.keymap.set('n', '<leader>fg', ':GFiles<CR>')
vim.keymap.set('n', '<leader>fl', ':Lines<CR>')
vim.keymap.set('n', '<leader>fw', ':Windows<CR>')
vim.keymap.set('n', '<leader>fh', ':History')
vim.keymap.set('n', '<leader>fc', ':Colors<CR>')
vim.keymap.set('n', '<leader>ft', ':Filetypes<CR>')
